"""create core data models

Revision ID: b6b080fcf436
Revises:
Create Date: 2026-06-08 13:47:08.941423
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = 'b6b080fcf436'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('style', sa.String(length=80), nullable=False),
    sa.Column('target_duration_sec', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('provider_configs',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('provider_type', sa.String(length=80), nullable=False),
    sa.Column('provider_name', sa.String(length=120), nullable=False),
    sa.Column('model_name', sa.String(length=160), nullable=False),
    sa.Column('api_key_ref', sa.String(length=255), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('default_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_configs_provider_name'), 'provider_configs', ['provider_name'], unique=False)
    op.create_index(op.f('ix_provider_configs_provider_type'), 'provider_configs', ['provider_type'], unique=False)
    op.create_index(op.f('ix_provider_configs_workspace_id'), 'provider_configs', ['workspace_id'], unique=False)
    op.create_table('assets',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_entity_id'), 'assets', ['entity_id'], unique=False)
    op.create_index(op.f('ix_assets_entity_type'), 'assets', ['entity_type'], unique=False)
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_provider'), 'assets', ['provider'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('chapters',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('outline', sa.Text(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('source_word_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_project_id'), 'chapters', ['project_id'], unique=False)
    op.create_index(op.f('ix_chapters_status'), 'chapters', ['status'], unique=False)
    op.create_table('characters',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role_type', sa.String(length=80), nullable=True),
    sa.Column('age', sa.String(length=40), nullable=True),
    sa.Column('gender', sa.String(length=40), nullable=True),
    sa.Column('identity', sa.String(length=255), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('fixed_prompt', sa.Text(), nullable=True),
    sa.Column('voice_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_project_id'), 'characters', ['project_id'], unique=False)
    op.create_index(op.f('ix_characters_status'), 'characters', ['status'], unique=False)
    op.create_table('generation_tasks',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_tasks_project_id'), 'generation_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_generation_tasks_provider'), 'generation_tasks', ['provider'], unique=False)
    op.create_index(op.f('ix_generation_tasks_status'), 'generation_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_generation_tasks_task_type'), 'generation_tasks', ['task_type'], unique=False)
    op.create_table('props',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visual_prompt', sa.Text(), nullable=True),
    sa.Column('story_function', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_props_project_id'), 'props', ['project_id'], unique=False)
    op.create_index(op.f('ix_props_status'), 'props', ['status'], unique=False)
    op.create_table('scenes',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visual_style', sa.Text(), nullable=True),
    sa.Column('atmosphere', sa.Text(), nullable=True),
    sa.Column('fixed_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_project_id'), 'scenes', ['project_id'], unique=False)
    op.create_index(op.f('ix_scenes_status'), 'scenes', ['status'], unique=False)
    op.create_table('exports',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=False),
    sa.Column('duration_sec', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('format', sa.String(length=40), nullable=False),
    sa.Column('ffmpeg_command', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_asset_id'), 'exports', ['asset_id'], unique=False)
    op.create_index(op.f('ix_exports_project_id'), 'exports', ['project_id'], unique=False)
    op.create_index(op.f('ix_exports_status'), 'exports', ['status'], unique=False)
    op.create_table('scripts',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scenes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dialogues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_chapter_id'), 'scripts', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_scripts_project_id'), 'scripts', ['project_id'], unique=False)
    op.create_index(op.f('ix_scripts_status'), 'scripts', ['status'], unique=False)
    op.create_table('shots',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('script_id', sa.String(length=36), nullable=True),
    sa.Column('scene_id', sa.String(length=36), nullable=True),
    sa.Column('shot_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('camera_shot', sa.String(length=120), nullable=True),
    sa.Column('camera_movement', sa.String(length=160), nullable=True),
    sa.Column('duration_sec', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dialogue_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('character_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prop_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('video_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('generation_mode', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shots_project_id'), 'shots', ['project_id'], unique=False)
    op.create_index(op.f('ix_shots_scene_id'), 'shots', ['scene_id'], unique=False)
    op.create_index(op.f('ix_shots_script_id'), 'shots', ['script_id'], unique=False)
    op.create_index(op.f('ix_shots_status'), 'shots', ['status'], unique=False)
    op.create_table('dialogues',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('script_id', sa.String(length=36), nullable=True),
    sa.Column('character_id', sa.String(length=36), nullable=True),
    sa.Column('shot_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('emotion', sa.String(length=80), nullable=True),
    sa.Column('start_time', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('end_time', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('audio_asset_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogues_audio_asset_id'), 'dialogues', ['audio_asset_id'], unique=False)
    op.create_index(op.f('ix_dialogues_character_id'), 'dialogues', ['character_id'], unique=False)
    op.create_index(op.f('ix_dialogues_project_id'), 'dialogues', ['project_id'], unique=False)
    op.create_index(op.f('ix_dialogues_script_id'), 'dialogues', ['script_id'], unique=False)
    op.create_index(op.f('ix_dialogues_shot_id'), 'dialogues', ['shot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialogues_shot_id'), table_name='dialogues')
    op.drop_index(op.f('ix_dialogues_script_id'), table_name='dialogues')
    op.drop_index(op.f('ix_dialogues_project_id'), table_name='dialogues')
    op.drop_index(op.f('ix_dialogues_character_id'), table_name='dialogues')
    op.drop_index(op.f('ix_dialogues_audio_asset_id'), table_name='dialogues')
    op.drop_table('dialogues')
    op.drop_index(op.f('ix_shots_status'), table_name='shots')
    op.drop_index(op.f('ix_shots_script_id'), table_name='shots')
    op.drop_index(op.f('ix_shots_scene_id'), table_name='shots')
    op.drop_index(op.f('ix_shots_project_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_scripts_status'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_project_id'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_chapter_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_exports_status'), table_name='exports')
    op.drop_index(op.f('ix_exports_project_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_asset_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_scenes_status'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_project_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_props_status'), table_name='props')
    op.drop_index(op.f('ix_props_project_id'), table_name='props')
    op.drop_table('props')
    op.drop_index(op.f('ix_generation_tasks_task_type'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_status'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_provider'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_project_id'), table_name='generation_tasks')
    op.drop_table('generation_tasks')
    op.drop_index(op.f('ix_characters_status'), table_name='characters')
    op.drop_index(op.f('ix_characters_project_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_chapters_status'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_project_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_provider'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_entity_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_entity_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_provider_configs_workspace_id'), table_name='provider_configs')
    op.drop_index(op.f('ix_provider_configs_provider_type'), table_name='provider_configs')
    op.drop_index(op.f('ix_provider_configs_provider_name'), table_name='provider_configs')
    op.drop_table('provider_configs')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
